image: mcr.microsoft.com/dotnet/sdk:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build Desu"
    artifacts:
      paths:
        - Desu/bin/

test:
    stage: test
    script: 
        - "dotnet test --verbosity normal"
